### ISSUE TITLE
Change the color

### ISSUE THREAD

**Issue by Soumyajit2825** [Soumyajit2825/Payment_Form#1]
- Change the background color and the hover effects and make it more attractive

**Comment by SaranshBaniyal** [comment]
@Soumyajit2825, good evening. Please assign this issue to me

**Comment by SaranshBaniyal** [comment]
@Soumyajit2825 where do you thing the hover effects should be added?

**Comment by Soumyajit2825** [comment]
@SaranshBaniyal at the submit now button

**Comment by jayantchaudhari18** [comment]
Hey @Soumyajit2825,I will it look more attractive. Please assign this system to me.

**Comment by jayantchaudhari18** [comment]
Hey @Soumyajit2825 ! I will make it look more attractive and apply suitable hover effects. Please assign this task to me.
