### ISSUE TITLE
change the color of the container

### ISSUE THREAD

**Issue by Soumyajit2825** [Soumyajit2825/Payment_Form#11]

**Comment by srigundeti10** [comment]
Assign me please

**Comment by Subhajit767** [comment]
hi

**Comment by Soumyajit2825** [comment]
@srigundeti10 sorry. This is a repo made for our college students.
you can find another one for your contributiuon

**Comment by srigundeti10** [comment]
> @srigundeti10 sorry. This is a repo made for our college students. you can find another one for your contributiuon

umm ok no problem
