### ISSUE TITLE
Make UI better

### ISSUE THREAD

**Issue by Krunal-Karena** [Soumyajit2825/Payment_Form#20]
I would like to improve UI of your website(form).

**Comment by Krunal-Karena** [comment]
Please assign me this issue.

**Comment by Soumyajit2825** [comment]
ok

**Comment by Krunal-Karena** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/99881021/195928135-69fa208d-3fe2-44a9-9227-2f15df336594.png)
![Screenshot (2)](https://user-images.githubusercontent.com/99881021/195928172-ba864391-a648-4bc5-a337-f9aa01d3af74.png)

**Comment by Krunal-Karena** [comment]
Please review this.

**Comment by Soumyajit2825** [comment]
yeah nice

**Comment by Krunal-Karena** [comment]
Any suggestion ?
