### ISSUE TITLE
Adding README.md file

### ISSUE THREAD

**Issue by Soumyajit2825** [Soumyajit2825/Payment_Form#21]
Make a readme file for this project
Make sure that you are doing these in the readme fille :- 

- Adding a snap-shot of the page
- Writing all about the project
- Writing how to do PR , how to find or create issues and also how to fork,pull,merge and push in the repository
- You can also add a contributors section 
**For reference see this REAME.md file below 👍🏻 **
[Readme sample](https://github.com/Soumyajit2825/MESSI_MANIA#readme)

**Comment by isaacmtp** [comment]
mate, I'll do this

**Comment by Soumyajit2825** [comment]
Ok fine

**Comment by Gunichi** [comment]
Can I do this?
