### ISSUE TITLE
Change the hover color of submit button

### ISSUE THREAD

**Issue by Koustavjr** [Soumyajit2825/Payment_Form#24]

**Comment by Koustavjr** [comment]
@Soumyajit2825 please assign me this issue :-)

**Comment by smitioswal** [comment]
Can I also work on this?

**Comment by smitioswal** [comment]
![image](https://user-images.githubusercontent.com/92663204/195869193-229a6fa2-7075-49db-836e-f6a4ea9a08b5.png)
I also made other styling changes and fixed some typos, let me know if it's okay
